
const scamPhrases = [
    { phrase: "hangup", type: "cmd" },
    { phrase: "hang up", type: "cmd" },
    { phrase: "hang on", type: "cmd" }, // Deepgram keeps mis-translating 'hang up' to 'hang on'
    { phrase: "i love you", type: "match" },
    { phrase: "soulmate", type: "match" },
    { phrase: "meant to be", type: "match" },
    { phrase: "help me", type: "match" },
    { phrase: "money for a ticket", type: "match" },
    { phrase: "urgent need", type: "match" },
    { phrase: "wedding plans", type: "match" },
    { phrase: "trust me", type: "match" },
    { phrase: "send me gift cards", type: "match" },
    { phrase: "i need your help", type: "match" },
    { phrase: "guaranteed return", type: "match" },
    { phrase: "risk free", type: "match" },
    { phrase: "act fast", type: "match" },
    { phrase: "limited time opportunity", type: "match" },
    { phrase: "secure your future", type: "match" },
    { phrase: "no risk", type: "match" },
    { phrase: "double your money", type: "match" },
    { phrase: "get rich quick", type: "match" },
    { phrase: "investment portfolio", type: "match" },
    { phrase: "exclusive deal", type: "match" },
    { phrase: "debt forgiveness", type: "match" },
    { phrase: "consolidate your loans", type: "match" },
    { phrase: "low interest rate", type: "match" },
    { phrase: "act now to reduce debt", type: "match" },
    { phrase: "past due payment", type: "match" },
    { phrase: "insurance claim overdue", type: "match" },
    { phrase: "urgent action required", type: "match" },
    { phrase: "policy cancellation", type: "match" },
    { phrase: "pay to reactivate", type: "match" },
    { phrase: "its me your grandson", type: "match" },
    { phrase: "help me out of trouble", type: "match" },
    { phrase: "i need bail money", type: "match" },
    { phrase: "dont tell mom", type: "match" },
    { phrase: "urgent family emergency", type: "match" },
    { phrase: "send money immediately", type: "match" },
    { phrase: "wire transfer needed", type: "match" },
    { phrase: "im in danger", type: "match" },
    { phrase: "please trust me", type: "match" },
    { phrase: "youve won", type: "match" },
    { phrase: "claim your prize", type: "match" },
    { phrase: "pay a fee to collect", type: "match" },
    { phrase: "cash transfer required", type: "match" },
    { phrase: "congratulations youre the winner", type: "match" },
    { phrase: "lottery winnings", type: "match" },
    { phrase: "exclusive prize claim", type: "match" },
    { phrase: "act fast to secure your prize", type: "match" },
    { phrase: "winner notification", type: "match" },
    { phrase: "your computer is at risk", type: "match" },
    { phrase: "remote access required", type: "match" },
    { phrase: "fix your account", type: "match" },
    { phrase: "service renewal", type: "match" },
    { phrase: "subscription fee", type: "match" },
    { phrase: "update your device", type: "match" },
    { phrase: "account locked", type: "match" },
    { phrase: "technical problem detected", type: "match" },
    { phrase: "call this number immediately", type: "match" },
    { phrase: "tax debt", type: "match" },
    { phrase: "unpaid taxes", type: "match" },
    { phrase: "irs agent", type: "match" },
    { phrase: "legal action required", type: "match" },
    { phrase: "arrest warrant issued", type: "match" },
    { phrase: "pay now to avoid penalties", type: "match" },
    { phrase: "urgent tax resolution", type: "match" },
    { phrase: "back taxes owed", type: "match" },
    { phrase: "settlement fee", type: "match" },
    { phrase: "tax relief services", type: "match" }
];

module.exports = { scamPhrases };
