const scamPhrases = [
    { phrase: 'hangup', type: 'cmd:hangup' },
    { phrase: 'hang up', type: 'cmd:hangup' },
    { phrase: 'hang on', type: 'cmd:hangup' },
    { phrase: 'add guardian', type: 'cmd:addGuardian' },
    { phrase: 'contact guardian', type: 'cmd:addGuardian' },
    { phrase: 'help guardian', type: 'cmd:addGuardian' },
    { phrase: 'i love you', type: 'phr' },
    { phrase: 'soulmate', type: 'phr' },
    { phrase: 'meant to be', type: 'phr' },
    { phrase: 'help me', type: 'phr' },
    { phrase: 'money for a ticket', type: 'phr' },
    { phrase: 'urgent need', type: 'phr' },
    { phrase: 'wedding plans', type: 'phr' },
    { phrase: 'trust me', type: 'phr' },
    { phrase: 'send me gift cards', type: 'phr' },
    { phrase: 'i need your help', type: 'phr' },
    { phrase: 'guaranteed return', type: 'phr' },
    { phrase: 'risk free', type: 'phr' },
    { phrase: 'act fast', type: 'phr' },
    { phrase: 'limited time opportunity', type: 'phr' },
    { phrase: 'secure your future', type: 'phr' },
    { phrase: 'no risk', type: 'phr' },
    { phrase: 'double your money', type: 'phr' },
    { phrase: 'get rich quick', type: 'phr' },
    { phrase: 'investment portfolio', type: 'phr' },
    { phrase: 'exclusive deal', type: 'phr' },
    { phrase: 'debt forgiveness', type: 'phr' },
    { phrase: 'consolidate your loans', type: 'phr' },
    { phrase: 'low interest rate', type: 'phr' },
    { phrase: 'act now to reduce debt', type: 'phr' },
    { phrase: 'past due payment', type: 'phr' },
    { phrase: 'insurance claim overdue', type: 'phr' },
    { phrase: 'urgent action required', type: 'phr' },
    { phrase: 'policy cancellation', type: 'phr' },
    { phrase: 'pay to reactivate', type: 'phr' },
    { phrase: 'its me your grandson', type: 'phr' },
    { phrase: 'help me out of trouble', type: 'phr' },
    { phrase: 'i need bail money', type: 'phr' },
    { phrase: 'dont tell mom', type: 'phr' },
    { phrase: 'urgent family emergency', type: 'phr' },
    { phrase: 'send money immediately', type: 'phr' },
    { phrase: 'wire transfer needed', type: 'phr' },
    { phrase: 'im in danger', type: 'phr' },
    { phrase: 'please trust me', type: 'phr' },
    { phrase: 'youve won', type: 'phr' },
    { phrase: 'claim your prize', type: 'phr' },
    { phrase: 'pay a fee to collect', type: 'phr' },
    { phrase: 'cash transfer required', type: 'phr' },
    { phrase: 'congratulations youre the winner', type: 'phr' },
    { phrase: 'lottery winnings', type: 'phr' },
    { phrase: 'exclusive prize claim', type: 'phr' },
    { phrase: 'act fast to secure your prize', type: 'phr' },
    { phrase: 'winner notification', type: 'phr' },
    { phrase: 'your computer is at risk', type: 'phr' },
    { phrase: 'remote access required', type: 'phr' },
    { phrase: 'fix your account', type: 'phr' },
    { phrase: 'service renewal', type: 'phr' },
    { phrase: 'subscription fee', type: 'phr' },
    { phrase: 'update your device', type: 'phr' },
    { phrase: 'account locked', type: 'phr' },
    { phrase: 'technical problem detected', type: 'phr' },
    { phrase: 'call this number immediately', type: 'phr' },
    { phrase: 'tax debt', type: 'phr' },
    { phrase: 'unpaid taxes', type: 'phr' },
    { phrase: 'irs agent', type: 'phr' },
    { phrase: 'legal action required', type: 'phr' },
    { phrase: 'arrest warrant issued', type: 'phr' },
    { phrase: 'pay now to avoid penalties', type: 'phr' },
    { phrase: 'urgent tax resolution', type: 'phr' },
    { phrase: 'back taxes owed', type: 'phr' },
    { phrase: 'settlement fee', type: 'phr' },
    { phrase: 'tax relief services', type: 'phr' },
];

module.exports = scamPhrases;
